version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2  # gunakan versi Node yang sesuai dengan React 18
    working_directory: ~/project

jobs:
  install_and_build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Build React App
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  build_workflow:
    jobs:
      - install_and_build